# Generated by Django 2.1.3 on 2018-12-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerialRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=30, blank=True, null=True)),
                ('longitude', models.CharField(max_length=30, blank=True, null=True)),
                ('speed', models.CharField(max_length=30, blank=True, null=True)),
            ],
        ),
    ]
