# Generated by Django 2.1.3 on 2018-12-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autokap_app', '0003_auto_20181205_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialread',
            name='buf',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='serialread',
            name='direction',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='serialread',
            name='line',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='serialread',
            name='status',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
